services:
  react:
    depends_on:
      - express
    build: ./REACT
    ports:
      - 5173:5173
    volumes:
      - ./REACT:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true

  express:
    depends_on:
      - mongodb
    build: ./EXPRESS
    ports:
      - 3000:3000
    volumes:
      - ./EXPRESS:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    
  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: sigrae_admin
      MONGO_INITDB_ROOT_PASSWORD: fredmenson-1234

volumes:
  mongodb: